name: Update NPM Dependencies
description: Check if the there are updates to NPM dependencies and create a pull request with the updated package.json and package-lock.json files.

inputs:
  base-branch:
    description: The branch used as the base for dependency update checks.
    default: main
    required: false

  target-branch:
    description: The branch where the pull request will be created.
    default: update-dependencies
    required: false
  
  working-directory:
    description: The working directory of the project to check for dependency updates.
    required: true
  
  gh-token:
    description: The GitHub token with repository access to write contents and  create pull requests.
    required: true
  
  debug:
    description: Enable debug mode for additional logging.  
    default: 'false'

runs:
  using: node20
  main: index.js