name: Update NPM Dependencies
description: Check if the there are updates to NPM dependencies and create a pull request with the updated package.json and package-lock.json files.

inputs:
  base-branch:
    description: The branch used as base for the dependency updates checks
    required: false
    default: main
  target-branch:
    description: The branch from which the pull request will be created
    required: false
    default: update-dependencies
  working-directory:
    description: The working directory of the project to check for dependency updates
    required: true
    default: .
  gh-token:
    description: The GitHub token used to create the pull request. Must have write access to the repository.
    #required: true
    default: ${{ secrets.GITHUB_TOKEN }}
  debug:
    description: Whether the output debug messages to the console
    #required: false
    default: 'false'

runs:
  using: node20
  main: index.js