name: 02 - Workflow Events
on:
    schedule:
      - cron: '* * * * *'
    
jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: Show the triggering event
          run: echo "Triggered by ${{ github.event_name }}"