name: 04 - Using Actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2   
      - name: Printing Folders  
        run: |
          echo "Current directory: $PWD"
          echo "Files in current directory:"
          ls -la    

  