name: 06 - contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug mode'
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: 'WORKFLOW_VAR'
  MY_OVERWRITTEN_VAR: 'WORKFLOW_OVERWRITTEN_VAR'
  
jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'JOB_VAR'
      MY_OVERWRITTEN_VAR: 'JOB_OVERWRITTEN_VAR'
      
    steps:
    - name: Show GitHub context information
      run: |
        echo "Triggered by ${{ github.event_name }}"
        echo "Reference is ${{ github.ref }}"
        echo "Actor is ${{ github.actor }}"
        echo "Workflow name is ${{ github.workflow }}"
        echo "Job name is ${{ github.job }}"
        echo "Run ID is ${{ github.run_id }}"
        echo "Run number is ${{ github.run_number }}"
    - name: Retrieve Variable
      run: |
        echo "The variable is ${{ vars.MY_VAR }}"
    - name: Retrieve Environment Variable
      env:
        MY_OVERWRITTEN_VAR: 'STEP_OVERWRITTEN_VAR'
      run: |
        echo "Workflow environment variable ${{ env.MY_WORKFLOW_VAR }}"
        echo "Overwritten workflow environment variable ${{ env.MY_OVERWRITTEN_VAR }}"
        
    - name: Retrieve Environment Variable with Job Context
      run: |
        echo "Workflow environment variable ${{ env.MY_WORKFLOW_VAR }}"
        echo "Overwritten workflow environment variable ${{ env.MY_OVERWRITTEN_VAR }}"
      
      