name: 07 - Using Expressions

on:
    push:
      branches:
        - main
    workflow_dispatch:
      inputs:
        debug:
          description: 'Enable debug mode'
          type: boolean
          default: false
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
        - name: Print start-up data
          if: ${{ inputs.debug  }}
          run: |
            echo "Triggered by ${{ github.event_name }}"
            echo "Branch is ${{ github.ref }}"
            echo "Commit SHA ${{ github.sha }}"
            echo "Runner OS is ${{ runner.os }}"

        - name: Print when triggered from main branch
          if: ${{ github.ref == 'refs/heads/main' && inputs.debug }}
          run: echo "This workflow was triggered from the main branch"

        - name: Greeting
          run: echo "Hello, world!"