name: 09 - Using Functions
on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize]
        branches: [main]
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failing Step
              run: exit 1
            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if previous steps succeed."
            - name: I will execute when any previous steps fail
              if: ${{ failure() }}
              run: echo "I will print if previous steps fail."  
            - name: I will always execute
              if: ${{ always() }}
              run: echo "I will always print, except when the workflow is cancelled."
            - name: I will execute when the workflow is cancelled
              if: ${{ cancelled() }}
              run: echo "I will print if the workflow is cancelled."
              