name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Skip deployment and only print build output'
        type: boolean
        default: false
      target:
        description: 'Deployment target environment'
        required: true
        type: environment
      tag:
        description: 'Release from which to build and deploy'
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Build Project
          run: echo "Building project from  tag ${{ inputs.tag }}"
          
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ inputs.dry-run == false }}
        steps:
        - name: Deploy to ${{ inputs.target }}
          run: echo "Deploying to environment ${{ inputs.target }} with tag ${{ inputs.tag }}"
