name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        description: 'Status of the build'
        type: choice
        options:
          - success
          - failure
        default: success


jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          build_status: ${{ steps.build.outputs.build_status }}
          output1: ${{ steps.build.outputs.output1 }}
          output2: ${{ steps.build.outputs.output2 }}
        steps:
        - name: Print GITHUB_OUTPUT path
          run: echo "GITHUB_OUTPUT is at $GITHUB_OUTPUT"
        
        - name: Build Project
          id: build
          run: |
            echo "Building project with status ${{ inputs.build-status }}"
            echo "build_status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
            echo "output1=value1" >> $GITHUB_OUTPUT
            echo "output2=value2" >> $GITHUB_OUTPUT
            cat $GITHUB_OUTPUT
            echo "mistake=true" > "$GITHUB_OUTPUT"
            cat $GITHUB_OUTPUT
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build_status == 'success' }}
        steps:
        - name: Deploy Project
          run: echo "Deploying project with build status ${{ needs.build.outputs.build_status }}"
        - name: Print Outputs
          run: |
                echo "Build Status: ${{ needs.build.outputs.build_status }}"
                echo "Output 1: ${{ needs.build.outputs.output1 }}"
                