name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
        use-cache:
            description: 'Use cache?'
            default: true
            type: boolean
        node-version:
            description: 'Node.js version to use'
            default: '21.x'
            type: choice
            options:
                - '21.x'
                - '20.x'
                - '18.x'
                - '16.x'
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ inputs.node-version }}
        
        - name: Cache Node Modules
          uses: actions/cache@v3
          if: ${{ inputs.use-cache == true }}
          id: cache-node-modules
          with:
            key: deps-node-modules-${{ hashFiles('13-caching/read-app/package-lock.json') }}
            path: |
              13-caching/react-app/node_modules

        - name: Install dependencies
          if: steps.cache-node-modules.outputs.cache-hit != 'true'
          run: |
            npm ci
         
        
        - name: Run Unit Tests
          run: |
            npm run test
          
        
        - name: Run Build
          run: |
            npm run build
          

        - name: Deploying to Non-Production
          run: |
            echo "Deploying to non-production environment..."