name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Perform some tests
        run: |
          echo "Running tests on Node.js version ${{ matrix.node-version }} on ${{ matrix.os }}"
          # Here you would typically run your tests, e.g., npm test