name: 16 - Working with Environments
on:
  workflow_dispatch:
    inputs:
        target-env:
            type: environment
            default: staging
            description: 'Select the environment to deploy to'

jobs:
  echo-staging:
    runs-on: ubuntu-latest
    environment: staging
    env:
        my-env-var: ${{ vars.MY_ENV_VALUE   || 'default-value' }}
    steps:
    - name: Print environment
      run: echo "Deploying to ${{ env.my-env-var }}"
    - name: 16 - Working with Environments | env - ${{ env.my-env-var }}
      run: |
       echo "Environment: ${{ env.my-env-var }}"
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod

    env:
        my-env-var: ${{ vars.MY_ENV_VALUE   || 'default-value' }}
    steps:
    - name: Print environment
      run: echo "Deploying to ${{ env.my-env-var }}"
    - name: 16 - Working with Environments | env - ${{ env.my-env-var }}
      run: |
       echo "Environment: ${{ env.my-env-var }}"
          