name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS

on:
  workflow_dispatch:

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install dependencies for custom JS action
            run: |
              cd .github/actions/js-dependency-update
              npm ci
              cd ../../../..

          - name: Check for dependency updates
            uses: ./.github/actions/js-dependency-update
            