name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        description: The URL to ping
        default: 'https://www.google.com'
      max_trials:
        description: Maximum number of trials to ping the URL
        default: '10'
        required: false
      delay:
        description: Delay in seconds between each ping
        default: '5'
        required: false

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping URL using custom Docker action
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}
          
