name: 18.1 - Reusable Workflows - Reusable Definition
on:
  workflow_call:
    inputs:
        target-directory:
            description: 'The target directory to build and deploy'
            required: true
            type: string
    outputs:
        build-status:
            description: 'The status of the build process'
            value: ${{ jobs.deploy.outputs.build-status }}
        url:
            description: 'The URL where the deployed artifacts can be accessed'
            value: ${{ jobs.deploy.outputs.url }}


jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.build-status }}
            url: ${{ steps.deploy.outputs.url }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
            
        - name: Build
          id: build
          run: |
            echo "Building using directory..."
            echo "build-status=success" >> $GITHUB_OUTPUT
        
        - name: Deploy
          id: deploy
          run: |
            echo "Deploying build artifacts..."
            echo "url=https://www.example.com" >> $GITHUB_OUTPUT
